apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloapp-dev
resources:
  - ../../base
images:
  - name: 939503809934.dkr.ecr.ap-southeast-2.amazonaws.com/helloapp
    newTag: sha-f9f243a
    newName: 939503809934.dkr.ecr.ap-southeast-2.amazonaws.com/helloapp
